/***************************************************************************
*.b
*  Copyright (c) 2000 DaimlerChrysler Rail Systems (North America) Inc
****************************************************************************
*  Project    : C167 FLASH Programming
*  File Name  : CPU_DEP.H
*  Subsystem  : Third stage boot loader
*  Procedures : N/A
*
*
*  Abstract   :
*  Compiler   :
*
*  EPROM Drawing:
*.b
*****************************************************************************
* History:
*  01 Apr 2000 D.Smail
*    Created
* Revised:
**************************************************************************/
/* storage definitions */
#define INT_8                           char
#define INT_16                          int
#define INT_32                          long
#define UINT_8                          unsigned char
#define UINT_16                         unsigned int
#define UINT_32                         unsigned long

#define FALSE                           0
#define TRUE                            1

